package nutricionistaapp.categorias;

public enum AntecedenteTipo {

    DIABETES,
    HIPERTENSION,
    CELIACO,
    RENAL,
    CANCER,
    ENFERMEDADES_RESPIRATORIAS,
    BULIMIA,
    ANOREXIA,
    ALZEIMER,
    PARKINSON,
    ALERGIA,
    COLITIS,
    HEMORROIDES,
    OSTEOPOROSIS,
    ACV,
    ACIDEZ,
    ANEMIA,
    OBESIDAD,
    ULCERAS_PEPTICAS,
    DESNUTRICION,
    HIPERTIROIDISMO,
    HIPOTIROIDISIMO,
    ESTRES,
    INSOMNIO,
    EPILEPSIA;

}
